### ISSUE TITLE
POST /api/comment permissions error

### ISSUE THREAD

**Issue by jvansanten** [skyportal/skyportal#1265]
In 92a46ae803472caea04b4f69d5f74b3129048cae as deployed on https://fritz.science, POST /api/comment with the following payload:

```
{"obj_id": "ZTF20acithxf", "text": "T2CatalogMatch", "attachment": {"body": "eyJ0aW1lc3RhbXAiOiAiMjAyMC0xMS0wMlQxMzo0MDo0NCIsICJydW4iOiAxNjQsICJkdXJhdGlvbiI6IDAuMjAzLCAicmVzdWx0IjogeyJTRFNTX3NwZWMiOiBmYWxzZSwgIk5FRHoiOiBmYWxzZSwgIlNEU1NEUjEwIjogZmFsc2UsICJicmVzY2lhIjogZmFsc2UsICJtaWxsaXF1YXMiOiBmYWxzZSwgIkdBSUFEUjIiOiB7ImRpc3QydHJhbnNpZW50IjogMjcuMTU0NDU3MjQ0NTk0MDksICJNYWdfRyI6IDE2LjA3MzA5NSwgIlBNUkEiOiAtOC41MjYyOTg3Mzc5MzUxOTgsICJFcnJQTVJBIjogMC4wODQyMTg4ODcyMzYwMjk1MSwgIlBNRGVjIjogLTEuOTM0NjE0MjM0NDYyMjMwOCwgIkVyclBNRGVjIjogMC4wNjcyMDExNDM1Njc5MjY4OSwgIlBseCI6IDEuMTEwMzExNTgzMjczNDcyNSwgIkVyclBseCI6IDAuMDQzMzM1NDQ1NjI0MDc0NDQ1LCAiRXhjZXNzTm9pc2UiOiAwLjAsICJFeGNlc3NOb2lzZVNpZyI6IDAuMH0sICJDUlRTX0RSMSI6IGZhbHNlLCAiQUFWU09WU1giOiBmYWxzZSwgIkxBTU9TVERSNCI6IGZhbHNlLCAiR0xBREV2MjMiOiBmYWxzZSwgImFsbFdJU0Vfc2t5bW90aW9uIjogZmFsc2UsICJ2b2lkR2FsUGFuIjogZmFsc2UsICJORUR6X2V4dGNhdHMiOiBmYWxzZX19", "name": "ZTF20acithxf.T2CatalogMatch.json"}}
```

raises:

```
Insufficient permissions.
```

even though the authorization token used has all permissions available to the issuing user (Classify, Comment, Upload data). Comments posted to other sources seem to work.

**Comment by acrellin** [comment]
@jvansanten is this a source that is viewable to you on the front-end?

**Comment by jvansanten** [comment]
Yes, I can see https://fritz.science/candidate/ZTF20acithxf as me.

**Comment by dannygoldstein** [comment]
@jvansanten does your token have the `Comment` ACL?

**Comment by dannygoldstein** [comment]
@jvansanten, in order to add a comment to an object, it currently needs to be a source (i.e., saved) not a candidate. since you can only see ZTF20acithxf as a candidate, it won't let you add a comment. 

relevant line of code: 

https://github.com/skyportal/skyportal/blob/master/skyportal/handlers/api/comment.py#L95

Do you still see this problem if you save the object to one of your groups as a source?

We are planning a major simplification of the source/obj/candidate API in the near future, so this should get easier soon. 

Thanks for bearing with us.

**Comment by acrellin** [comment]
Closing in favor of https://github.com/skyportal/skyportal/issues/1312
