### ISSUE TITLE
delete button missing in quick source search field

### ISSUE THREAD

**Issue by scizen9** [skyportal/skyportal#1752]
The quick source search bar used to have a delete button when the field was filled in and the user wanted to do a new search.
That button has now disappeared.

This is the search field in the left-hand panel on any page.

**Comment by joelachance** [comment]
@scizen9 , is this the 'X' that populates when something is entered in the field?

**Comment by scizen9** [comment]
> @scizen9 , is this the 'X' that populates when something is entered in the field?

Yes.

**Comment by joelachance** [comment]
Ok, apologies-- I removed this because it was just not playing nicely with the loader. There were a lot of occurrences where both the loader and the 'X' were present, and it just doesn't look great. I should have let you guys know, and this one fell through the cracks. It seems like any of the entries that might populate the search bar were around 5-10 characters, and while the 'X' is nice, I wasn't sure it was necessary.

I'm happy to bring it back, but I'd vote to fix the issue where they render over each other. If that sounds good, I'd like to update the title of this ticket (and leave it as a bug).

**Comment by stefanv** [comment]
Given that you can double click and start typing, I don't think the X is a big deal.

**Comment by acrellin** [comment]
I agree that it doesn't seem like a big deal --it's easy to clear it out

**Comment by joelachance** [comment]
If everyone is happy leaving the 'X' out, let's close this ticket!

**Comment by stefanv** [comment]
@scizen9 Let us know if you feel strongly about it. We can always reopen!
