### ISSUE TITLE
"updateChildren" part of normalize probabilities in taxonomies (MultipleClassificationsForm.jsx)

### ISSUE THREAD

**Issue by AshishMahabal** [skyportal/skyportal#2366]
Currently if parent value is increased, non-zero values of children are scaled.
They should not be.

In SCoPe taxonomy, for instance, if I decide something is bogus at 0.5,
then drag the "galaxy" child to 0.5,
then drag bogus to 0.75, galaxy gets dragged to 0.75 too.
I may feel that the object is bogus at 0.75, but is a galaxy only at 0.5

const newProbability =
        parseFloat(
          (
            (newValue * currentProbability) /
            totalProbabilityOfSubclasses
          ).toFixed(3)
        ) || 0;

**Comment by AshishMahabal** [comment]
I don't speak much react (close to 0), so here is some pseudocode in lieu of a PR:

- do *NOT* update children. Why should only non-zero children be updated? I may not even have all my children in the taxonomy
- do *NOT* update siblings. For the same reasons above
- update parent *only* upward. Use max(children) instead of sum(children) [need to cap goes away automatically].

**Comment by mcoughlin** [comment]
@bfhealy Please consider and suggest what behavior would be best for labeling these taxonomy trees.

**Comment by bfhealy** [comment]
@mcoughlin I've been thinking about this today and was wondering where this labeling functionality (sliders and scaling) is found on Skyportal/Fritz. On a Source page, I only see the option to select a classification from a dropdown and type in a probability. Is this what the manual classifiers used to create the golden dataset?

I generally agree with Ashish's points above - it is appropriate to leave open the possibility for uncertainty in child/sibling labels by not propagating an increase in parent probability down to them. The direction of updating should only be from child to parent.

On the question of capping child probabilities, SCOPE's use of independent binary classifiers (rather than a single multi-class classifier) on ZTF data could support using max() instead of sum() to eliminate the need for a cap. This implementation would come at the expense of the probabilities potentially not summing to 1 at the leaves of the tree.

**Comment by mcoughlin** [comment]
@bfhealy What about in the candidate scanning tab? It's been a minute, but I think we ended up dropping them there (this is functionality translated from the variable star marshal to fritz a minute ago).

Ok let's see what maybe makes the most sense once you do a bit of labeling so we can figure out what you find best?

**Comment by mcoughlin** [comment]
@bfhealy I checked and I think sitewide group + going back in time seems to have them. But I realized they are in the group sources dropdown in the table, see GIF here: https://github.com/skyportal/skyportal/pull/2120

**Comment by bfhealy** [comment]
After more consideration I continue to agree with Ashish's suggestions for changing the slider behavior as described above. The current behavior leads to some potentially unintended results, and since Scope uses binary classifiers, switching to max(children) instead of sum(children) will not raise the issues that it would for multi-label classification.
