### ISSUE TITLE
Group Error

### ISSUE THREAD

**Issue by anticharmquark** [skyportal/skyportal#250]
Hi,
I have been given admin privileges in a skyportal group, but upon trying to access the group, I receive a "Group Not Found" error, along with the error code: "API Error: Could not fetch data from servers (400)". I know the  group exists but can not access it.

Thanks,
David

**Comment by acrellin** [comment]
Hi @anticharmquark , can you please provide more details on the issue so that we can offer assistance?  What is the URL you are using to attempt to view the group?  What is the group ID (not its name)?  Can you confirm that the group admin sees your username (email address) on the list of group members?  Can you confirm that you are signed in to SkyPortal with that same handle (the email address displayed on the top right of the page)?  Thanks

**Comment by acrellin** [comment]
Closing: Did not receive enough information from user to reproduce.
