### ISSUE TITLE
Scanning shifter rota

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2540]
Some collaborations designate scanning rotas, and it would be nice if SkyPortal had features that enabled that. This might fit best as a feature of groups, which already have groups of users, and in this case, the admin could also specify start and end dates for scanning for group members. Other quality of life features could include:

- [ ]  Would be good if the shifter received an email 30 min before start of shift (your shift will start XX, and your shift will end XX)
- [ ]  Convert to “local time” with setting timezone
- [ ]  Display the names and contacts from the others shifters on at the same time
- [ ]  The app can send a slack message to alert the shifters

**Comment by profjsb** [comment]
Can you provide a mock of what the interface would look like on the front end?

**Comment by santier14** [comment]
Additional requirements

- [ ] A shifter is called A follow-up advocate Shifter
- [ ] Be able to “manage your shift” under your profile. In GRANDMA - ICARE, if you weren’t on shift, you couldn’t annotate the transients. So you had “super-administrator” rights only during the period of your shifts. Otherwise, you were needed to click a button with “request F-A power”
- [ ] You can go to “manage your shifter”, change your schedule and visualize when you are under shift
- [ ] I think one thing that should be great is to have a list of shifters  PER campaign (GW, etc …) 
- [ ] you can click and be able to “exchange” or assign your shift period to someone else. Like “Give the shift to …”
- [ ] I think it should be also useful to have a table that summarizes the number of hours of shifts over the last 3 months or 6 months
- [ ] You need to have also a button to link to a documentation about “how to be on shifter” 
- [ ] and another button to a “demo” e.g an event that a shifter can annotate as a testing shifter event. For GRANDMA, padawan FAs really enjoyed to exercices

**Comment by mcoughlin** [comment]
<img width="624" alt="Screen Shot 2022-01-16 at 5 37 59 AM" src="https://user-images.githubusercontent.com/2291947/149658286-8b2f61f6-7af0-492b-93e9-c6de7c946df0.png">
<img width="622" alt="Screen Shot 2022-01-16 at 5 38 16 AM" src="https://user-images.githubusercontent.com/2291947/149658288-0f20e839-9de0-4c7c-bf5a-a0c1b66fd257.png">
<img width="621" alt="Screen Shot 2022-01-16 at 5 38 29 AM" src="https://user-images.githubusercontent.com/2291947/149658289-dc0bdfa6-5fda-45a2-b79a-e9a24ca72cf7.png">

**Comment by guynir42** [comment]
@mcoughlin is this addressed by the latest "shifts" PRs?

**Comment by mcoughlin** [comment]
@guynir42 Let's close it once those PRs go in and we can open more specific issues for other stuff.
