### ISSUE TITLE
Filtering sources by comments/annotations bug

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#2944]
Right now the filtering on sources for annotations/comments (e.g., using `commentsFilter`) happens after the pagination code reduces the total number of output sources. 
If you are only filtering on comments/annotations, it is very likely that some sources that would have passed your filtering criteria are not loaded in the 100-500 sources allowed in that call. You will get a subset of the sources on the first page. 
While it is possible to iterate over all pages with multiple queries, this is inefficient and the user will not be aware of this. 

Solution 1 is to refactor the filtering to be on the SQL select side. 
Solution 2 is to query everything and only page the results before sending them back (I think this is preferable). This will also help clean up the filtering/sorting of paged results.

**Comment by mcoughlin** [comment]
@guynir42 If we query everything, check for comments, and then paginate, I think we will be trouble because we do the check in that source loop so that's tough. I guess you are thinking to do the query like here: https://github.com/skyportal/skyportal/blob/main/skyportal/handlers/api/candidate.py#L1191
before pagination and do the loop over sources, removing any that don't pass? 

It seems like maybe better would be to rethink this as SQL, although it looks to beyond our immediate know-how. It isn't *that* different from the other filtering, but annotations doesn't seem doable that way, maybe comments are but I think _in is  exact match plus our comments are stored kind of weirdly.

**Comment by guynir42** [comment]
@mcoughlin There may be ways to speed this up, e.g., querying only objects with annotations of the proper key and/or origin could be helpful. 
In the end, this is a slow query if you (a) have lots of sources with that annotation and (b) don't use any other criteria. 
So I'm thinking to do this properly means to do it slowly sometimes. So we just have to figure out a way to do slow requests (e.g., using a read-only DB). 

I don't have a magic solution to this, unfortunately.

**Comment by mcoughlin** [comment]
I think we got this one.
