### ISSUE TITLE
Auto-add Javascript extensions

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#306]
Automate the addition of all existing components (no more manual imports), and also add in extensions from a user extension directory, making it possible for external developers to add to SkyPortal without adding files into the "main" directory structure where all the other components are kept.

**Comment by dannygoldstein** [comment]
Updating this following our discussions on skyportal extension best practices. We have decided to move away from the separate extensions/ directory model for extending skyportal and instead are encouraging users to fork the skyportal repo, modify the skyportal code within the repository as needed, merging in origin/master to stay up to date with the main repository. 

The first part of this issue is still open, I believe (correct me if I am work @stefanv, @acrellin ).

**Comment by stefanv** [comment]
JavaScript components can be hooked in via the config file as explicit routes.

We are figuring out the details on how to manage patches on SkyPortal for changes that are too invasive to utilize existing extension mechanisms.
