### ISSUE TITLE
Investigate: are we following best pinning practices

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#312]

**Comment by joelachance** [comment]
From what I'm seeing in the `package.json`, this is pretty typical from other projects I've been apart of. `npm` does have some pinning options,  which are laid out pretty well here: https://semver.npmjs.com/

From what I've seen in other projects, the most used are the carat `^` and the squiggly (technical term) `~`. Carat gives you the latest version with its major, and the squiggly gives you the latest version within its minor.

Some other tricks I find useful are using `npm i --save-exact some-package@1.1.1`, and more importantly, `npm audit`. This will generate a report notifying you of any out-of-date packages, which you can then (mostly) fix with `npm audit fix`. Yarn has some additional tools around upgrades, if folks want to head down that path.

**Comment by stefanv** [comment]
Thanks for this summary, @joelachance!

We currently use `npm-check` for updates, and have a bot that makes PRs every month to test updates.

Do you think we should switch to using `~` over fully pinned?

**Comment by joelachance** [comment]
@stefanv I think it's worth sticking with how you currently have it. Without opening a can of worms here, there's some confusing behavior as you introduce `package-lock.json` with packages pinned with `^` and `~`. An example of this would be installing a package and pinning the version to `^1.0.0`. This is going to be tagged in the `package-lock` as the exact version (`1.0.0`), and not `^1.0.0`. So when you run an `npm install`, the `package.json` version is going to supersede the `package-lock`, and there might be developers with slightly different `node_modules` versions. This is _maybe_ an issue. I'll also note a lot of very popular JS projects (React, etc.) use `^` for most packages, so whatever direction SkyPortal heads in I really think would be OK. Some backstory here:

https://github.com/npm/npm/issues/17979
https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json

I don't know if there's been updates since, but I think it's fair to say that pinning exact versions as you have been will yield something that's going to be reproducible for everyone. You can of course use `^` and `~`, but there's a chance the `package-lock.json` may not be respected. The main benefit of both variations is that you'll get what are likely some security updates without having to run an audit or a check, but given the inconsistencies, I'm not sure its worth it (especially since you have a bot doing this work).

**Comment by stefanv** [comment]
That's very helpful, thanks @joelachance !  We don't ship a `package-lock.json`, but sounds like with precise version pinning we probably don't need to either.

With your research, I feel comfortable closing this :pray:
