### ISSUE TITLE
Photometry distinct origin query very slow

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3186]
I think we need to add an index or something on origin?

Query | Database | Load by total time | Avg execution time (ms) | Times called | Avg rows returned
-- | -- | -- | -- | -- | --
SELECT DISTINCT photometry.origin AS photometry_origin FROM photometry | fritz-1 |   | 326,421.15 | 3 | 8

**Comment by thomasculino** [comment]
I thought that the origin column was already indexed. That is why we decided to use this query in this beginning. However, if the origin column is indexed and is still too slow, we can set a list of commonly used origins so that the execution time to display the list of origins on the profile page will not be long. And if the origin is not in the list, the user can add manually the name of the origin he wants to filter next to the list of hard coded ones.

**Comment by mcoughlin** [comment]
Ah good point @thomasculino, you are right about the index. When is the query triggered? Is it just the user profile page?

**Comment by thomasculino** [comment]
It should only be triggered there yes, just in the OriginSelect.jsx which is used only once in the profile page.

**Comment by thomasculino** [comment]
I can try making it async
