### ISSUE TITLE
Errors on duplicate token deletion, creation; on adding invalid user to group

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#344]
- [ ] When clicking rapidly on "delete" in the token list, you can click a token twice before it is deleted. This results in a red API error box.  Token delete should be disabled immediately upon click.  This issue may be relevant to groups as well.
- [ ] When attempting to create a token with a name that is already taken, red box.
- [ ] When adding an invalid username to a group, red error box.

**Comment by acrellin** [comment]
Regarding the first issue, the error message is informative, so this doesn't seem to be a problem. If a user accidentally double-clicks twice, they'll see a message saying "No such token" for the second click. This seems fine. The second issue is addressed in #354 

The last issue doesn't seem valid - we display a perfectly informative error message ("Invalid username"). What's the issue here?

**Comment by stefanv** [comment]
Maybe we should help people look up users on the system, like GitHub does when you add people to teams.  You type a few letters, and then we auto-complete on their names.  Not urgent.

**Comment by acrellin** [comment]
Yes, that'd be a nice thing to have. I'll look into how that's typically
implemented.

**Comment by acrellin** [comment]
@stefanv I was going to start adding this, but realized we should probably ask the group if this raises any privacy concerns (this effectively exposes all usernames). Thoughts?

**Comment by stefanv** [comment]
We should check, yes, but my thinking was that it's a bit unreasonable to expect group managers to remember the correct email addresses.  I'll write a message to the group.
