### ISSUE TITLE
Missing desu filter

### ISSUE THREAD

**Issue by igorandreoni** [skyportal/skyportal#4197]
The u-band filter is missing for DECam ("desu")
http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=CTIO/DECam.u

**Comment by mcoughlin** [comment]
@igorandreoni This looks to be an issue with sncosmo: 
https://sncosmo.readthedocs.io/en/stable/bandpass-list.html
do you have time to get a PR there open?
I have a recent example here with Gaia:
https://github.com/sncosmo/sncosmo/pull/351
https://github.com/sncosmo/sncosmo.github.io/pull/29

Otherwise I could work on opening a PR with them

**Comment by igorandreoni** [comment]
yes I'll do that, thanks @mcoughlin
