### ISSUE TITLE
Plot gcn event times in sources

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#4226]
Relaying request from MMA call:

Right now we have sources which are associated to gcn events. The GCN events have times. It would be great if we could plot these event times in the source lightcurves, perhaps with a vertical dashed line.

**Comment by Theodlz** [comment]
@robertdstein just to be sure. These 2 concepts (sources you mark as associated to an event from the source list in the GCN Event page) should be linked? Or do you just want that on any source page, you can pick any gcnevent to display a line at its trigger time on the photometry plot?

I am asking because if its the first, that means you already know that source happened after an event and marked it as such, so not sure why that line on the plot is useful there.

**Comment by robertdstein** [comment]
So previously when I was opening up fritz pages for some sources, it would say "associated to xxxx event", though clicking through some random ones I don't see it anymore.

Anyway, what we specifically want: 

If a source is associated to an event, i.e in a GCN event page source table (perhaps excluding rejected sources but definitely including both confirmed and undefined), then we want to be able to see easily when the event happened relative to the detections. We are not using it to see whether an event was detected beforehand (that's covered by filtering). Instead, it is very important to easily how much later after an event detections have happened. A detection at +5 hours is different than +50 hours, but on the scale of the plots it's not easy to work out which category it is.

**Comment by Theodlz** [comment]
Ok gotcha. So yes this is what I imagined @mcoughlin. They wanna see events on the plot in general. Because the challenge here @robertdstein is that we query sources on the fly right. Unless a user sets or unsets a status there is no record that a source is in an event. If we did, the database would be flooded by any random sources saved to any group that happens to be inside of any event + that would add a lot of overhead everytime someone saves a source and said sources gets new photometry or when we get new events...

What about, a dropdown menu just like the on the candidate scanning page. There you can pick an event and then we display it on the plot. Otherwise, it can be something like a button where when you click it regenerates the plot + queries events that occurred up to N days before first detection and that contain the source, and then plots lines/markers for each.

Anyway I don't think this can be or should be an automatic thing, as spatial queries can be pretty expensive. For anyone doing MMA stuff waiting a little might be reasonable, but we don't want to end up impacting the user experience of everyone that uses a source page.

**Comment by Theodlz** [comment]
@robertdstein the dropdown menu thingy is basically the existing feature of the spectrum plot to show a custom line. There you set a wavelength, but here you would pick an event and a line would show at the mjd when the event happens. 

That's just an idea, but this seems to be the most reasonable one.
