### ISSUE TITLE
Decide on granularity for followup request priorities 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#603]
Why isn't this numerical? And does it have to be enumerated? Does it make sense to have a priority 1.5, which would slot it between 1 and 2?

_Originally posted by @profjsb in https://github.com/skyportal/skyportal/pull/574#discussion_r456685645_

This issue serves as a forum to determine the right way to enumerate / define follow-up priorities, continuing the conversation started by @profjsb above.

**Comment by dmitryduev** [comment]
@dannygoldstein can we close this?

**Comment by kmshin1397** [comment]
@scizen9 Thoughts on this from the SEDM point of view?

**Comment by scizen9** [comment]
Actually,  making this a float with a limited range would solve a problem we're grappling with now.
Targets that pass the BTS filter, but are fainter than 18.5  get assigned a default low priority of 1.
Turns out not all faint targets are created equal, and ones within the i-band coverage are more
interesting. We would like to assign these a priority of 1.5 so they get observed before the ones
outside the i-band coverage, but Fritz offers no way to do this, currently.
