### ISSUE TITLE
db_init.py for non-root

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#968]
I am using Docker to run SkyPortal on NERSC.  I would like to clear my database with `make db_clear`.  NERSC does not allow containers to be run as root.  `sudo` is thus not possible.

**Comment by stefanv** [comment]
We use `sudo -u postgres` to execute all database commands so that we have access to the database.

Three potential solutions:

- write a fake `sudo` script that ignores arguments
- patch db_init.py line 64 and set sudo = ''
- add a flag to db_init.py such as `--no-sudo`

**Comment by AlexGKim** [comment]
I am using an external filesystem for the database.  So I am running into two issues.

It appears that my local user has to have the same user ID was the owner of the external file.  The only way I could see doing that is by hardwiring the user ID inside the image, which is not ideal.

Even after hardwiring the user ID inside the image, I get the following error when running through web.  It is clear that this app should have access to this database file?

> [✗] Removing existing databases
> Could not delete database: 
> 
>   dropdb: error: could not connect to database template1: could not connect to server: No such file or directory
>         Is the server running locally and accepting
>         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by dannygoldstein** [comment]
@AlexGKim: @stefanv and I had a long discussion yesterday about refactoring the `db_init` and `db_clear` Makefile directives to run as a non-root user on Linux systems.  The upshot of the discussion was that there are no blockers in principle to running these directives as non-root users on Linux systems. The main reason we are using root now is because of the way postgres is installed by default on linux systems using `apt`. `apt` writes files into directories that require root access to write to. We agreed to investigate the non-root approach to managing postgres on linux further.

**Comment by acrellin** [comment]
@alexgkim is this still a current request on your end?

**Comment by AlexGKim** [comment]
Indeed yes.  Our interest now has evolved into fritz, not just SkyPortal.
